from enum import Enum


class ApiConstants(str, Enum):
    BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR'
    INVALID_ADDRESS_ERROR = 'INVALID_ADDRESS_ERROR'
    UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR'
    USER_ALREADY_EXISTS_ERROR = 'USER_ALREADY_EXISTS_ERROR'
    USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR'
