# Generated by Django 4.1.12 on 2023-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tx_id', models.TextField()),
                ('value', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
